### ISSUE TITLE
Is there a reason that this repository doesn't carry an MIT license?

### ISSUE THREAD

**Issue by whyisjake** [mattcg/language-subtag-registry#7]
Just wondering why `ODC-By-1.0` was chosen over `MIT`.

**Comment by Nerlin** [comment]
Can you add the license text into LICENSE.md file and put this file to the root of your repo please?
This helps various automated tools to gather package licenses and include them to other projects to refer the author.

You can also publish your package to npm with this license file included. This will allow libraries like license-checker to identify it automatically. https://www.npmjs.com/package/license-checker

The same thing can be done with https://github.com/mattcg/language-tags repo.
Thank you.

**Comment by jeffpaul** [comment]
So interestingly enough, `package.json` references `ODC-By-1.0`: https://github.com/mattcg/language-subtag-registry/blob/0cb1beee755e489fbf5ff7c4134f3e4362a61f41/package.json#L23

...while `README.md`'s "Credits and collaboration references `MIT`: https://github.com/mattcg/language-subtag-registry/blob/master/README.md#credits-and-collaboration
> Update scripts copyright (c) 2013, [Matthew Caruana Galizia](https://twitter.com/mcaruanagalizia) and licensed under and [MIT license](http://mattcg.mit-license.org/).

...and `/scripts/importer.js` references `MIT`: https://github.com/mattcg/language-subtag-registry/blob/0cb1beee755e489fbf5ff7c4134f3e4362a61f41/scripts/importer.js#L3

So @mattcg it seems like maybe `package.json` mistakenly references `ODC-By-1.0` and should be `MIT`?  If that's the case, please confirm and I can push up a PR to make that change and add a `LICENSE.md` file to the repo with the explicit MIT license for GitHub to parse/display accordingly... thanks!

**Comment by mattcg** [comment]
Thanks for the prompt @whyisjake - switched to an MIT license exclusively.

**Comment by mattcg** [comment]
Actually, solved this a different way. The update script is excluded from the NPM package. That way, only ODC-BY licensed content is included.
