### ISSUE TITLE
Is it possible to switch to MIT license?

### ISSUE THREAD

**Issue by igoradamenko** [mattcg/language-subtag-registry#8]
Hey Matthew!

Thank you for the package 🐨 

We want to use it in our projects as a transitive dependency coming from eslint-plugin-jsx-a11y:

```
eslint-plugin-jsx-a11y@6.4.1 → language-tags@1.0.5 → language-subtag-registry@0.3.21
```

But it is not possible due to ODC-By-1.0 license. It is kind of hard to make sure that this license works in our country, so we're a bit scared and can't use this package. Especially because ODC-By-1.0 [is not marked as FSF Free by SPDX](https://spdx.org/licenses/).

Is it possible to relicense it with MIT?

**Comment by igoradamenko** [comment]
Ping @mattcg 🐱

**Comment by angwoo** [comment]
@mattcg Any update on this?

**Comment by davidtaylorhq** [comment]
Is there a particular reason for the choice of ODC-By-1.0? IANA have a fairly recent (November 2021) statement on licensing here: https://www.iana.org/help/licensing-terms

> to avoid any potential confusion about applicable rights, both IANA and IETF desire to (a) dedicate any applicable copyright rights that they may own in the Protocol Registries to the public domain, and (b) license any copyright or related rights for which they are a licensee (with a right to sublicense) to the broadest extent that they are permitted to do so. Accordingly, both IANA and IETF affirm that any applicable rights that they may have in the Protocol Registries are subject to the Creative Commons CC0 1.0 dedication found at https://creativecommons.org/publicdomain/zero/1.0/legalcode.

**Comment by mattcg** [comment]
Hi David, no good reason. I think I added it at a time when I knew little about licenses... which is still the case! What license would say is best to use here?

**Comment by davidtaylorhq** [comment]
The [licensing terms](https://www.iana.org/help/licensing-terms) on the IANA website give details about the licensing of their source data (which I think this repo is based on?). They mention 'CC0 1.0', which is included in the list of FSF Free licenses which @igoradamenko linked in the OP.

But I'm afraid I'm not a lawyer and don't have any particular knowledge about licensing, so can't really advise on what license you should apply to this package.
